version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 20
