language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

script:
  - mvn -B -V clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.organization=vrampal-bitbucket -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3cfa5215365fddaab012358aae78fb4008c856c1
