language: java

sudo: false

jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: "vrampal-bitbucket"

cache:
  directories:
    - $HOME/.m2/repository

script:
  - mvn -B -V clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar
